### ISSUE TITLE
Video cutscenes don't work

### ISSUE THREAD

**Issue by blockbreaker177** [jigsaw-4277821/Psych-Engine-0.5-Android-Port#16]
### Describe your bug here.

Video cutscenes don't work so the song won't start unless I remove the mp4 from the videos folder

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Randomxdp** [comment]
The webview isnt implemented in this port

**Comment by D3MONSLAY3R101** [comment]
> The webview isnt implemented in this port

Oh ok

**Comment by blockbreaker177** [comment]
> The webview isnt implemented in this port

Oh ok
